### PR TITLE
Allow relativ loading of dbn networks from conf

### PR DESCRIPTION
**Pull request by jpoeppel**
DBNSpec currently assumes that the network xbif-files for b0 and 2tbn are located in the working directory. This fix will always search for those files relative to the directory of the conf-file.

### CODE REVIEW

**Comment by hbuschme** [comment]
Looks good so far.

As an edge case we could check whether xbfi-files in the spec are referenced with an absolute path and, if so, use it as such. Or do you think that would be to much?

**Comment by jpoeppel** [comment]
How would you go about distinguishing absolut from relativ paths? Starting with "/"?

**Comment by hbuschme** [comment]
`os.path` has a function `isabs` that does this.

**Comment by jpoeppel** [comment]
I know, but this basically just means it starts with a "/" (for unix systems). I am fine with adding it when we document it somewhere explicitly (we should document the structure of the conf files anyways).

**Comment by hbuschme** [comment]
I agree, especially as I had problems explaining it myself yesterday. I created an issue: #18

**Pull request merged**
